SELECT 
    INV.DATE_ AS [TARİH], 
    ISNULL(LGUSER.NAME, '') AS [KULLANICI_ADI], -- Kim yakmış bu faturayı görelim
    CASE INV.TRCODE 
        WHEN 1 THEN 'Satınalma Faturası' 
        WHEN 3 THEN 'Toptan Satış İade Faturası' 
        WHEN 4 THEN 'Alınan Hizmet Faturası' 
        WHEN 13 THEN 'Satınalma Fiyat Farkı Faturası' 
        WHEN 14 THEN 'Satış Fiyat Farkı Faturası' 
        ELSE 'Diğer' END AS [FATURA_TÜRÜ],
    INV.FICHENO AS [FATURA_NO], 
    CLD.DEFINITION_ AS [CARİ_UNVAN],
    STL.VAT AS [KDV_ORANI], 
    STL.VATAMNT AS [ÖN_MUH_KDV_TUTARI], 
    ISNULL(EML.MUH_KDV, 0) AS [GENEL_MUH_KDV_TUTARI],
    ISNULL(EML.ACCOUNTCODE, 'HESAP BULUNAMADI') AS [MUH_HESAP_KODU]
FROM LG_{FIRMNR}_01_STLINE STL WITH(NOLOCK)
JOIN LG_{FIRMNR}_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF = STL.INVOICEREF
LEFT JOIN LG_{FIRMNR}_CLCARD CLD WITH(NOLOCK) ON INV.CLIENTREF = CLD.LOGICALREF
-- Kullanıcı tablosunu buraya bağladık
LEFT JOIN L_CAPIUSER LGUSER ON INV.CAPIBLOCK_CREATEDBY = LGUSER.NR
LEFT JOIN (
    -- Muhasebe tarafı (191'li hesaplar)
    SELECT 
        ACCFICHEREF, 
        ACCOUNTCODE,
        CASE 
            WHEN ACCOUNTCODE IN ('191.01.001', '191.02.001') THEN 1
            WHEN ACCOUNTCODE IN ('191.01.004', '191.02.004') THEN 10
            WHEN ACCOUNTCODE IN ('191.01.005', '191.02.005') THEN 20
        END AS ORAN,
        SUM(DEBIT - CREDIT) AS MUH_KDV
    FROM LG_{FIRMNR}_01_EMFLINE WITH(NOLOCK)
    WHERE ACCOUNTCODE IN ('191.01.001', '191.01.004', '191.01.005','191.02.001', '191.02.004', '191.02.005' )
      AND CANCELLED = 0 
    GROUP BY ACCFICHEREF, ACCOUNTCODE
) EML ON INV.ACCFICHEREF = EML.ACCFICHEREF AND STL.VAT = EML.ORAN 

WHERE INV.CANCELLED = 0 
  AND STL.CANCELLED = 0 
  AND INV.TRCODE IN (1, 3, 4,13,14) 
  AND STL.LINETYPE NOT IN (2, 3) 
  AND INV.DATE_ BETWEEN '20260101' AND '20261231'
