SELECT
    ACC.CODE AS HESAP_KODU,
    ACC.DEFINITION_ AS HESAP_ACIKLAMASI,
    EMFL.DATE_ AS TARIH,
    EMF.FICHENO AS FIS_NO,
    EMF.JOURNALNO AS YEVMIYE_NO,
    INV.FICHENO AS FATURA_NO,
    EMFL.LINEEXP AS ACIKLAMA,

    CASE EMFL.TRCODE
        WHEN 1 THEN 'Açılış'
        WHEN 2 THEN 'Tahsil Fişi'
        WHEN 3 THEN 'Tediye Fişi'
        WHEN 4 THEN 'Mahsup Fişi'
        WHEN 6 THEN 'Kur Farkı'
        WHEN 7 THEN 'Kapanış Fişi'
        ELSE 'Bilinmiyor'
    END AS FIS_TURU,

    CASE
        WHEN EMFL.LINEEXP LIKE '%TOPTAN SATIŞ FATURASI%' THEN 'Toptan Satış Faturası'
        WHEN EMFL.LINEEXP LIKE '%VERİLEN HİZMET FATURASI%' THEN 'Verilen Hizmet Faturası'
        WHEN EMFL.LINEEXP LIKE '%ALINAN HİZMET FATURASI%' THEN 'Alınan Hizmet Faturası'
        WHEN EMFL.LINEEXP LIKE '%SATINALMA FATURASI%' THEN 'Satınalma Faturası'
        WHEN EMFL.LINEEXP LIKE '%SATIŞ İADE FATURASI%' THEN 'Satış İade Faturası'
        WHEN EMFL.LINEEXP LIKE '%SATINALMA İADE FATURASI%' THEN 'Satınalma İade Faturası'
        WHEN EMFL.LINEEXP LIKE '%SATINALMA FİYAT FARKI FATURASI%' THEN 'Satınalma Fiyat Farkı Faturası'
        WHEN EMFL.LINEEXP LIKE '%SATIŞFİYAT FARKI FATURASI%' THEN 'Satış Fiyat Farkı Faturası'
        WHEN EMFL.LINEEXP LIKE '%ALINAN SERBEST MESLEK MAKBUZU%' THEN 'Alınan Serbest Meslek Makbuuzu'
        ELSE 'Diğer'
    END AS FATURA_TURU,

    EMFL.DEBIT AS BORC,
    EMFL.CREDIT AS ALACAK,
    
    -- Zaman Bilgileri
    EMF.CAPIBLOCK_CREADEDDATE AS EKLEME_TARIHI,
    EMF.CAPIBLOCK_MODIFIEDDATE AS DEGISTIRME_TARIHI,
    
    -- Kullanıcı Bilgileri
    U1.NAME AS EKLEYEN_KULLANICI,
    U2.NAME AS SON_DEGISTIREN_KULLANICI

FROM LG_{FIRMNR}_01_EMFLINE EMFL
LEFT JOIN LG_{FIRMNR}_01_EMFICHE EMF ON EMF.LOGICALREF = EMFL.ACCFICHEREF
LEFT JOIN LG_{FIRMNR}_01_INVOICE INV ON INV.LOGICALREF = EMF.SOURCEFREF
LEFT JOIN LG_{FIRMNR}_EMUHACC ACC ON ACC.LOGICALREF = EMFL.ACCOUNTREF
-- Kullanıcı tablolarını bağlıyoruz
LEFT JOIN L_CAPIUSER U1 ON U1.NR = EMF.CAPIBLOCK_CREATEDBY
LEFT JOIN L_CAPIUSER U2 ON U2.NR = EMF.CAPIBLOCK_MODIFIEDBY

WHERE EMFL.DATE_ BETWEEN '2026-01-01' AND '2026-12-31'
