SELECT 
    INV.DATE_ AS [TARIH],
    INV.FICHENO AS [FATURA NO],
    INV.DOCODE AS [BELGE NO],
    
    -- FATURA TÜRÜ ÇEVİRİSİ (TRCODE)
    CASE INV.TRCODE 
        WHEN 1 THEN 'Satınalma Faturası' 
        WHEN 8 THEN 'Toptan Satış Faturası' 
        WHEN 6 THEN 'Satınalma İade Faturası' 
        WHEN 4 THEN 'Alınan Hizmet Faturası' 
        WHEN 13 THEN 'Satınalma Fiyat Farkı Faturası' 
        WHEN 3 THEN 'Toptan Satış İade Faturası' 
        WHEN 9 THEN 'Verilen Hizmet Faturası' 
        WHEN 14 THEN 'Satış Fiyat Farkı Faturası' 
        ELSE 'Diğer' 
    END AS [FATURA TÜRÜ],
    
    CLD.CODE AS [CARİ HESAP KODU],
    CLD.DEFINITION_ AS [UNVAN],
    CLD.TAXOFFICE AS [VERGİ DAİRESİ],
    
    -- Kimlik No (TAXNR veya TCKNO)
    ISNULL(NULLIF(CLD.TAXNR,''), CLD.TCKNO) AS [KİMLİK NO], 
    
    -- TOPLAMA İŞLEMLERİ
    SUM(STL.VATMATRAH) AS [MATRAH],
    SUM(STL.ADDTAXAMOUNT) AS [EK VERGİ MATRAH],
    SUM(STL.VATAMNT) AS [KDV TUTARI],
    SUM(STL.VATMATRAH + STL.VATAMNT) AS [FATURA TOPLAMI],
    
    INV.TRADINGGRP AS [TICARI_ISLEM_GRUBU],
    
    -- Fiyat Farkı Türü (DECPRDIFF)
    CASE 
        WHEN INV.TRCODE IN (13, 14) AND INV.DECPRDIFF = 1 THEN 'AZALTILACAK' 
        WHEN INV.TRCODE IN (13, 14) AND INV.DECPRDIFF = 0 THEN 'ARTIRILACAK' 
        ELSE '' 
    END AS [TÜRÜ],
    
    -- MAKSİMUM değerler
    MAX(STL.DEDUCTIONPART1) AS [TEVKIFAT_PAY],
    MAX(STL.DEDUCTIONPART2) AS [TEVKIFAT_PAYDA],
    MAX(STL.DEDUCTCODE) AS [TEVKIFAT_KODU],
    MAX(STL.VATEXCEPTCODE) AS [KDV_MUAFIYET_KODU],
    
    -- Kullanıcı Adı ve Özel Kod
    ISNULL(LGUSER.NAME, '') AS [KULLANICI ADI], 
    INV.SPECODE AS [FATURA_OZEL_KODU], 
    INV.DOCTRACKINGNR AS [BELGE İZLEME NO],
    
   
    CASE INV.CANCELLED
        WHEN 1 THEN 'EVET İPTAL' 
        WHEN 0 THEN 'HAYIR' 
        ELSE 'BİLİNMİYOR'
    END AS [İPTAL DURUMU]
    
-- TABLOLAR (Firma Numarası {FIRMNR} ile)
FROM 
    LG_{FIRMNR}_01_STLINE STL 
LEFT JOIN 
    LG_{FIRMNR}_01_INVOICE INV ON INV.LOGICALREF = STL.INVOICEREF 
LEFT JOIN 
    LG_{FIRMNR}_CLCARD CLD ON INV.CLIENTREF = CLD.LOGICALREF 
LEFT JOIN 
    L_CAPIUSER LGUSER ON INV.CAPIBLOCK_CREATEDBY = LGUSER.NR 

-- FİLTRELER
WHERE 
 
    INV.DATE_ BETWEEN '20260101' AND '20261231' 
    AND INV.TRCODE IN (1, 8, 6, 4, 13, 3, 9, 14) 
    AND STL.LINETYPE NOT IN (2, 3, 7) 
   AND INV.CANCELLED IN (0, 1)

-- GRUPLAMA
GROUP BY 
    INV.DATE_, INV.FICHENO, INV.DOCODE, CLD.CODE, CLD.DEFINITION_, CLD.TAXOFFICE, 
    CLD.TAXNR, CLD.TCKNO, INV.TRADINGGRP, INV.TRCODE, INV.DECPRDIFF, INV.DOCTRACKINGNR, 
    LGUSER.NAME, INV.SPECODE, INV.CANCELLED
