SELECT
    CLC.CODE AS [CARİ KODU],
    CLC.DEFINITION_ AS [CARİ ADI],
    CLC.SPECODE3 AS [İŞYERİ],
    
    -- SON HAREKET TARİHİ: NULL yerine '1900-01-01' kullanarak hatayı engelliyoruz
    MAX(CASE WHEN CLF.CANCELLED = 0 THEN CLF.DATE_ ELSE '1900-01-01' END) AS [SON HAREKET TARIHI],
    
    -- HAREKETSİZ AY SAYISI
    DATEDIFF(MONTH, MAX(CASE WHEN CLF.CANCELLED = 0 THEN CLF.DATE_ ELSE '1900-01-01' END), GETDATE()) AS [Hareketsiz Ay Sayısı],
    
    -- GÜNCEL BAKİYE: Mükerrer satırları ayıklanmış gerçek bakiye
    ROUND(SUM(CASE WHEN CLF.CANCELLED = 0 AND CLF.PAIDINCASH = 0 
              THEN (CASE WHEN CLF.SIGN = 0 THEN CLF.AMOUNT ELSE -CLF.AMOUNT END) 
              ELSE 0 END), 2) AS [GÜNCEL BAKİYE]
    
FROM
    LG_{FIRMNR}_CLCARD CLC WITH(NOLOCK)
LEFT JOIN
    LG_{FIRMNR}_01_CLFLINE CLF WITH(NOLOCK) ON CLC.LOGICALREF = CLF.CLIENTREF
    
GROUP BY
    CLC.CODE, CLC.DEFINITION_, CLC.LOGICALREF,CLC.SPECODE3
    
HAVING 
    MAX(CASE WHEN CLF.CANCELLED = 0 THEN CLF.DATE_ ELSE '1900-01-01' END) > '1900-01-01'
