SELECT 
    ACC.CODE, 
    ACC.DEFINITION_, 
    USR.NAME, 
    ACC.CAPIBLOCK_CREADEDDATE
FROM 
    LG_{FIRMNR}_EMUHACC ACC WITH(NOLOCK)
LEFT JOIN 
    L_CAPIUSER USR ON ACC.CAPIBLOCK_CREATEDBY = USR.NR
WHERE 
    ACC.CAPIBLOCK_CREADEDDATE BETWEEN '2026-01-01 00:00:00' AND '2026-12-31 23:59:59'
