SELECT
    INV.DATE_ AS [TARİH],
    INV.FICHENO AS [FİŞ_NO],
    INV.DOCODE AS [BELGE_NO],
    CASE INV.TRCODE
        WHEN 1 THEN 'Satınalma'
        WHEN 8 THEN 'Satış'
        WHEN 6 THEN 'Satınalma İade'
        WHEN 3 THEN 'Satış İade'
        WHEN 4 THEN 'Alınan Hizmet'
        WHEN 9 THEN 'Verilen Hizmet'
        WHEN 13 THEN 'Satınalma Fiyat Farkı'
        WHEN 14 THEN 'Satış Fiyat Farkı'
        ELSE 'Diğer'
    END AS [FATURA_TÜRÜ],
    CLD.CODE AS [CARİ_KODU],
    CLD.DEFINITION_ AS [CARİ_ADI],
    CASE
        WHEN STL.LINETYPE IN (0,1,6,7,8) THEN ISNULL(ITM.CODE, '')
        WHEN STL.LINETYPE = 4 THEN ISNULL(SRV.CODE, '')
        ELSE ''
    END AS [KALEM_KODU],
    CASE
        WHEN STL.LINETYPE IN (0,1,6,7,8) THEN ISNULL(ITM.NAME, '')
        WHEN STL.LINETYPE = 4 THEN ISNULL(SRV.DEFINITION_, '')
        ELSE ''
    END AS [KALEM_AÇIKLAMASI],
    STL.AMOUNT AS [MİKTAR],
    STL.PRICE AS [BİRİM_FİYAT],
    STL.VATMATRAH AS [KDV_MATRAH],
    STL.VAT AS [KDV_%],
    STL.VATAMNT AS [KDV_TUTAR],
    (STL.VATMATRAH + STL.VATAMNT) AS [SATIR_NET_TOPLAM],
    INV.NETTOTAL AS [FATURA_NET_TOPLAM]
FROM LG_{FIRMNR}_{PERIODNRPP}_STLINE STL WITH(NOLOCK)
INNER JOIN LG_{FIRMNR}_{PERIODNRPP}_INVOICE INV WITH(NOLOCK)
    ON INV.LOGICALREF = STL.INVOICEREF
LEFT JOIN LG_{FIRMNR}_CLCARD CLD WITH(NOLOCK)
    ON CLD.LOGICALREF = INV.CLIENTREF
LEFT JOIN LG_{FIRMNR}_ITEMS ITM WITH(NOLOCK)
    ON ITM.LOGICALREF = STL.STOCKREF
LEFT JOIN LG_{FIRMNR}_SRVCARD SRV WITH(NOLOCK)
    ON SRV.LOGICALREF = STL.STOCKREF
WHERE
    INV.CANCELLED = 0
    AND STL.LINETYPE NOT IN (2,3)
    AND INV.DATE_ BETWEEN '2026-01-01' AND '2026-12-31'
ORDER BY
    INV.DATE_, INV.FICHENO, STL.INVOICELNNO;
