SELECT 
    INV.DATE_ AS [TARİH], 
    INV.FICHENO AS [FİŞ NO], 
    INV.DOCODE AS [BELGE_NO], 
    CASE INV.TRCODE 
        WHEN 1 THEN 'Satınalma Faturası' 
        WHEN 8 THEN 'Toptan Satış Faturası' 
        WHEN 6 THEN 'Satınalma İade Faturası' 
        WHEN 4 THEN 'Alınan Hizmet Faturası' 
        WHEN 13 THEN 'Satınalma Fiyat Farkı Faturası' 
        WHEN 3 THEN 'Toptan Satış İade Faturası' 
        WHEN 9 THEN 'Verilen Hizmet Faturası' 
        WHEN 14 THEN 'Satış Fiyat Farkı Faturası' 
        ELSE 'Diğer' 
    END AS [FATURA_TURU], 
    
    DIV.NAME AS [İŞYERİ], 
    CLD.CODE AS [CARİ HESAP KODU], 
    CLD.DEFINITION_ AS [CARİ ADI], 
    CLD.TAXOFFICE AS [VERGİ DAİRESİ], 
    ISNULL(NULLIF(CLD.TAXNR, ''), CLD.TCKNO) AS [KİMLİK_NO], 
    CASE 
        WHEN STL.LINETYPE IN (0,6,7,1,8) THEN ISNULL(ITM.CODE,'') 
        WHEN STL.LINETYPE = 4 THEN ISNULL(SRV.CODE,'') 
        ELSE '' 
    END AS [MALZEME_HİZMET_KODU], 
    CASE 
        WHEN STL.LINETYPE IN (0,6,7,1,8) THEN ITM.NAME 
        WHEN STL.LINETYPE = 2 THEN 'İNDİRİM' 
        WHEN STL.LINETYPE = 4 THEN SRV.DEFINITION_ 
        ELSE '' 
    END AS [AÇIKLAMA], 
    STL.AMOUNT AS [MİKTAR], 
    ISNULL(UNT.NAME,'') AS [BİRİMİ], 
    ISNULL(ITM.GTIPCODE, '') AS [GTIP_NO], 
    CASE 
        WHEN STL.LINETYPE IN (0,6,7,1,8) THEN ISNULL(ITMU.VOLUME_, 0)
        ELSE 0
    END AS [HACİM], 
    STL.VATMATRAH AS [KDV_MATRAH], 
    STL.ADDTAXAMOUNT AS [EK_VERGİ], 
    STL.VATAMNT AS [KDV_TUTARI], 
    STL.VAT AS [KDV_ORANI], 
    STL.DEDUCTCODE AS [TEVKİFAT_KODU], 
    INV.TRADINGGRP AS [TİCARİ_İŞLEM_GRUBU], 
    ISNULL(LGUSER.NAME,'') AS [KULLANICI ADI], 
    INV.SPECODE AS [FATURA_ÖZEL_KODU], 
    CASE 
        WHEN INV.TRCODE IN (13,14) THEN 
            CASE 
                WHEN INV.DECPRDIFF = 1 THEN 'AZALTILACAK' 
                WHEN INV.DECPRDIFF = 0 THEN 'ARTIRILACAK' 
                ELSE '' 
            END 
        ELSE '' 
    END AS [FİYAT_FARKI_TÜRÜ], 
    STL.OWNER AS [MAL SAHİBİ], 
    STL.SPECODE2 AS [HAREKET_ÖZEL_KODU2], 
    ISNULL(ACC.CODE, '') AS [MUH_KODU], 
    ISNULL(ACC.DEFINITION_, '') AS [MUH_AÇIKLAMASI],
    ISNULL(VATACC.CODE, '') AS [KDV_MUH_KODU], 
    ISNULL(VATACC.DEFINITION_, '') AS [KDV_MUH_ACIKLAMASI]

FROM LG_{FIRMNR}_{PERIODNRPP}_STLINE STL WITH(NOLOCK)
LEFT JOIN LG_{FIRMNR}_{PERIODNRPP}_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF = STL.INVOICEREF 
LEFT JOIN LG_{FIRMNR}_CLCARD CLD WITH(NOLOCK) ON INV.CLIENTREF = CLD.LOGICALREF 
LEFT JOIN LG_{FIRMNR}_ITEMS ITM WITH(NOLOCK) ON ITM.LOGICALREF = STL.STOCKREF 
LEFT JOIN LG_{FIRMNR}_UNITSETL UNT WITH(NOLOCK) ON STL.UOMREF = UNT.LOGICALREF 
LEFT JOIN LG_{FIRMNR}_SRVCARD SRV WITH(NOLOCK) ON STL.STOCKREF = SRV.LOGICALREF 
LEFT JOIN LG_{FIRMNR}_ITMUNITA ITMU WITH(NOLOCK) ON ITMU.ITEMREF = STL.STOCKREF AND ITMU.LINENR = 1
LEFT JOIN L_CAPIUSER LGUSER WITH(NOLOCK) ON INV.CAPIBLOCK_CREATEDBY = LGUSER.NR 

LEFT JOIN LG_{FIRMNR}_EMUHACC ACC WITH(NOLOCK) ON STL.ACCOUNTREF = ACC.LOGICALREF 
LEFT JOIN LG_{FIRMNR}_EMUHACC VATACC WITH(NOLOCK) ON STL.VATACCREF = VATACC.LOGICALREF 

LEFT JOIN L_CAPIDIV DIV WITH(NOLOCK) ON INV.BRANCH = DIV.NR AND DIV.FIRMNR = {FIRMNR}

WHERE 
    INV.DATE_ BETWEEN '2026-01-01' AND '2026-12-31' 
    AND INV.CANCELLED = 0
    AND STL.LINETYPE NOT IN (2,3,7)
