SELECT 
    CLC.CODE AS [CARİ_HESAP_KODU], 
    CLC.DEFINITION_ AS [CARİ_HESAP_AÇIKLAMASI], 
    CLC.SPECODE3 AS [FABRİKA],
    ACC.CODE AS [MUHASEBE_HESAP_KODU],
    ACC.DEFINITION_ AS [MUHASEBE_HESAP_AÇIKLAMASI],
    
    ISNULL((SELECT ROUND(SUM(CASE WHEN CLFL.SIGN = 0 THEN CLFL.AMOUNT ELSE -CLFL.AMOUNT END), 2)
     FROM LG_{FIRMNR}_01_CLFLINE CLFL WITH(NOLOCK)
     WHERE CLFL.CLIENTREF = CLC.LOGICALREF 
     AND CLFL.CANCELLED = 0
     AND CLFL.PAIDINCASH = 0 
    ), 0) AS [ÖN_MUHASEBE_BAKİYE],
     
    ISNULL((SELECT ROUND(SUM(EMFL.DEBIT - EMFL.CREDIT), 2)
     FROM LG_{FIRMNR}_01_EMFLINE EMFL WITH(NOLOCK)
     WHERE EMFL.ACCOUNTREF = ACC.LOGICALREF
     AND EMFL.CANCELLED = 0
    ), 0) AS [GENEL_MUHASEBE_BAKİYE],

    ROUND(
        ISNULL((SELECT SUM(CASE WHEN CLFL.SIGN = 0 THEN CLFL.AMOUNT ELSE -CLFL.AMOUNT END) FROM LG_{FIRMNR}_01_CLFLINE CLFL WHERE CLFL.CLIENTREF = CLC.LOGICALREF AND CLFL.CANCELLED = 0 AND CLFL.PAIDINCASH = 0), 0) -
        ISNULL((SELECT SUM(EMFL.DEBIT - EMFL.CREDIT) FROM LG_{FIRMNR}_01_EMFLINE EMFL WHERE EMFL.ACCOUNTREF = ACC.LOGICALREF AND EMFL.CANCELLED = 0), 0)
    , 2) AS [BAKİYE_FARKI]

FROM 
    LG_{FIRMNR}_CLCARD CLC WITH(NOLOCK)
LEFT JOIN 
    LG_{FIRMNR}_CRDACREF CRA WITH(NOLOCK) ON CLC.LOGICALREF = CRA.CARDREF AND CRA.TYP = 1
LEFT JOIN 
    LG_{FIRMNR}_EMUHACC ACC WITH(NOLOCK) ON CRA.ACCOUNTREF = ACC.LOGICALREF

WHERE 
    CLC.ACTIVE = 0
